// source: file_create.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var file_pb = require('./file_pb.js');
goog.object.extend(proto, file_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
goog.exportSymbol('proto.bigfile.file_create.FileCreateRequest', null, global);
goog.exportSymbol('proto.bigfile.file_create.FileCreateRequest.OperationCase', null, global);
goog.exportSymbol('proto.bigfile.file_create.FileCreateResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bigfile.file_create.FileCreateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.bigfile.file_create.FileCreateRequest.oneofGroups_);
};
goog.inherits(proto.bigfile.file_create.FileCreateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bigfile.file_create.FileCreateRequest.displayName = 'proto.bigfile.file_create.FileCreateRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bigfile.file_create.FileCreateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bigfile.file_create.FileCreateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bigfile.file_create.FileCreateResponse.displayName = 'proto.bigfile.file_create.FileCreateResponse';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.bigfile.file_create.FileCreateRequest.oneofGroups_ = [[7,8,9,10,11]];

/**
 * @enum {number}
 */
proto.bigfile.file_create.FileCreateRequest.OperationCase = {
  OPERATION_NOT_SET: 0,
  OVERWRITE: 7,
  RENAME: 8,
  APPEND: 9,
  CREATE_DIR: 10,
  NONE: 11
};

/**
 * @return {proto.bigfile.file_create.FileCreateRequest.OperationCase}
 */
proto.bigfile.file_create.FileCreateRequest.prototype.getOperationCase = function() {
  return /** @type {proto.bigfile.file_create.FileCreateRequest.OperationCase} */(jspb.Message.computeOneofCase(this, proto.bigfile.file_create.FileCreateRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bigfile.file_create.FileCreateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.bigfile.file_create.FileCreateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bigfile.file_create.FileCreateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bigfile.file_create.FileCreateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    token: jspb.Message.getFieldWithDefault(msg, 1, ""),
    path: jspb.Message.getFieldWithDefault(msg, 2, ""),
    secret: (f = msg.getSecret()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    hidden: (f = msg.getHidden()) && google_protobuf_wrappers_pb.BoolValue.toObject(includeInstance, f),
    overwrite: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    rename: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    append: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
    createDir: jspb.Message.getBooleanFieldWithDefault(msg, 10, false),
    none: jspb.Message.getBooleanFieldWithDefault(msg, 11, false),
    content: (f = msg.getContent()) && google_protobuf_wrappers_pb.BytesValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bigfile.file_create.FileCreateRequest}
 */
proto.bigfile.file_create.FileCreateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bigfile.file_create.FileCreateRequest;
  return proto.bigfile.file_create.FileCreateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bigfile.file_create.FileCreateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bigfile.file_create.FileCreateRequest}
 */
proto.bigfile.file_create.FileCreateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setToken(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setSecret(value);
      break;
    case 6:
      var value = new google_protobuf_wrappers_pb.BoolValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.BoolValue.deserializeBinaryFromReader);
      msg.setHidden(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setOverwrite(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRename(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAppend(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCreateDir(value);
      break;
    case 11:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setNone(value);
      break;
    case 12:
      var value = new google_protobuf_wrappers_pb.BytesValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.BytesValue.deserializeBinaryFromReader);
      msg.setContent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bigfile.file_create.FileCreateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bigfile.file_create.FileCreateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bigfile.file_create.FileCreateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bigfile.file_create.FileCreateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getToken();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSecret();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getHidden();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_wrappers_pb.BoolValue.serializeBinaryToWriter
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeBool(
      7,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeBool(
      8,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeBool(
      9,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeBool(
      10,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 11));
  if (f != null) {
    writer.writeBool(
      11,
      f
    );
  }
  f = message.getContent();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      google_protobuf_wrappers_pb.BytesValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional string token = 1;
 * @return {string}
 */
proto.bigfile.file_create.FileCreateRequest.prototype.getToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.bigfile.file_create.FileCreateRequest.prototype.setToken = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string path = 2;
 * @return {string}
 */
proto.bigfile.file_create.FileCreateRequest.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.bigfile.file_create.FileCreateRequest.prototype.setPath = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.StringValue secret = 4;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.bigfile.file_create.FileCreateRequest.prototype.getSecret = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 4));
};


/** @param {?proto.google.protobuf.StringValue|undefined} value */
proto.bigfile.file_create.FileCreateRequest.prototype.setSecret = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.bigfile.file_create.FileCreateRequest.prototype.clearSecret = function() {
  this.setSecret(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bigfile.file_create.FileCreateRequest.prototype.hasSecret = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.BoolValue hidden = 6;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.bigfile.file_create.FileCreateRequest.prototype.getHidden = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.BoolValue, 6));
};


/** @param {?proto.google.protobuf.BoolValue|undefined} value */
proto.bigfile.file_create.FileCreateRequest.prototype.setHidden = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.bigfile.file_create.FileCreateRequest.prototype.clearHidden = function() {
  this.setHidden(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bigfile.file_create.FileCreateRequest.prototype.hasHidden = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional bool overwrite = 7;
 * @return {boolean}
 */
proto.bigfile.file_create.FileCreateRequest.prototype.getOverwrite = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/** @param {boolean} value */
proto.bigfile.file_create.FileCreateRequest.prototype.setOverwrite = function(value) {
  jspb.Message.setOneofField(this, 7, proto.bigfile.file_create.FileCreateRequest.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 */
proto.bigfile.file_create.FileCreateRequest.prototype.clearOverwrite = function() {
  jspb.Message.setOneofField(this, 7, proto.bigfile.file_create.FileCreateRequest.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bigfile.file_create.FileCreateRequest.prototype.hasOverwrite = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional bool rename = 8;
 * @return {boolean}
 */
proto.bigfile.file_create.FileCreateRequest.prototype.getRename = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/** @param {boolean} value */
proto.bigfile.file_create.FileCreateRequest.prototype.setRename = function(value) {
  jspb.Message.setOneofField(this, 8, proto.bigfile.file_create.FileCreateRequest.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 */
proto.bigfile.file_create.FileCreateRequest.prototype.clearRename = function() {
  jspb.Message.setOneofField(this, 8, proto.bigfile.file_create.FileCreateRequest.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bigfile.file_create.FileCreateRequest.prototype.hasRename = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional bool append = 9;
 * @return {boolean}
 */
proto.bigfile.file_create.FileCreateRequest.prototype.getAppend = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/** @param {boolean} value */
proto.bigfile.file_create.FileCreateRequest.prototype.setAppend = function(value) {
  jspb.Message.setOneofField(this, 9, proto.bigfile.file_create.FileCreateRequest.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 */
proto.bigfile.file_create.FileCreateRequest.prototype.clearAppend = function() {
  jspb.Message.setOneofField(this, 9, proto.bigfile.file_create.FileCreateRequest.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bigfile.file_create.FileCreateRequest.prototype.hasAppend = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional bool create_dir = 10;
 * @return {boolean}
 */
proto.bigfile.file_create.FileCreateRequest.prototype.getCreateDir = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/** @param {boolean} value */
proto.bigfile.file_create.FileCreateRequest.prototype.setCreateDir = function(value) {
  jspb.Message.setOneofField(this, 10, proto.bigfile.file_create.FileCreateRequest.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 */
proto.bigfile.file_create.FileCreateRequest.prototype.clearCreateDir = function() {
  jspb.Message.setOneofField(this, 10, proto.bigfile.file_create.FileCreateRequest.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bigfile.file_create.FileCreateRequest.prototype.hasCreateDir = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional bool none = 11;
 * @return {boolean}
 */
proto.bigfile.file_create.FileCreateRequest.prototype.getNone = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 11, false));
};


/** @param {boolean} value */
proto.bigfile.file_create.FileCreateRequest.prototype.setNone = function(value) {
  jspb.Message.setOneofField(this, 11, proto.bigfile.file_create.FileCreateRequest.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 */
proto.bigfile.file_create.FileCreateRequest.prototype.clearNone = function() {
  jspb.Message.setOneofField(this, 11, proto.bigfile.file_create.FileCreateRequest.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bigfile.file_create.FileCreateRequest.prototype.hasNone = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional google.protobuf.BytesValue content = 12;
 * @return {?proto.google.protobuf.BytesValue}
 */
proto.bigfile.file_create.FileCreateRequest.prototype.getContent = function() {
  return /** @type{?proto.google.protobuf.BytesValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.BytesValue, 12));
};


/** @param {?proto.google.protobuf.BytesValue|undefined} value */
proto.bigfile.file_create.FileCreateRequest.prototype.setContent = function(value) {
  jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.bigfile.file_create.FileCreateRequest.prototype.clearContent = function() {
  this.setContent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bigfile.file_create.FileCreateRequest.prototype.hasContent = function() {
  return jspb.Message.getField(this, 12) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bigfile.file_create.FileCreateResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.bigfile.file_create.FileCreateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bigfile.file_create.FileCreateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bigfile.file_create.FileCreateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    requestId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    file: (f = msg.getFile()) && file_pb.File.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bigfile.file_create.FileCreateResponse}
 */
proto.bigfile.file_create.FileCreateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bigfile.file_create.FileCreateResponse;
  return proto.bigfile.file_create.FileCreateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bigfile.file_create.FileCreateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bigfile.file_create.FileCreateResponse}
 */
proto.bigfile.file_create.FileCreateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setRequestId(value);
      break;
    case 2:
      var value = new file_pb.File;
      reader.readMessage(value,file_pb.File.deserializeBinaryFromReader);
      msg.setFile(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bigfile.file_create.FileCreateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bigfile.file_create.FileCreateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bigfile.file_create.FileCreateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bigfile.file_create.FileCreateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequestId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getFile();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      file_pb.File.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint64 request_id = 1;
 * @return {number}
 */
proto.bigfile.file_create.FileCreateResponse.prototype.getRequestId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.bigfile.file_create.FileCreateResponse.prototype.setRequestId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bigfile.file.File file = 2;
 * @return {?proto.bigfile.file.File}
 */
proto.bigfile.file_create.FileCreateResponse.prototype.getFile = function() {
  return /** @type{?proto.bigfile.file.File} */ (
    jspb.Message.getWrapperField(this, file_pb.File, 2));
};


/** @param {?proto.bigfile.file.File|undefined} value */
proto.bigfile.file_create.FileCreateResponse.prototype.setFile = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.bigfile.file_create.FileCreateResponse.prototype.clearFile = function() {
  this.setFile(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bigfile.file_create.FileCreateResponse.prototype.hasFile = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.bigfile.file_create);
